### ISSUE TITLE
Change 'Continue reading' to 'more' in blog.

### ISSUE THREAD

**Issue by ycchan-IES** [SRLab-Code-Club/SRLab-YC-Site#2]
Change 'Continue reading' to 'more' in blog.

**Comment by lcabon258** [comment]
[commit 16be36e](https://github.com/SRLab-Code-Club/SRLab-YC-Site/commit/16be36e44543a56cff006f4b6ad7de834bdeb3dd) add the custom translation file.
Issue closed.
